version: '3.9'


services:

  backend:
    build: 
      context: ./
    environment:
      - SECRET=ASDHKULYHMAKJDSjahskdlhgakdwHUIDHAW
    ports:
      - "8000:8000"
    # volumes:
    #   - /app
 

